# Generated by Django 3.1.7 on 2021-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('food', 'food'), ('cell_phones', 'Cell_phones'), ('cars', 'cars')], default='other'),
        ),
    ]
